// Shared car data used across QuoteModal components

export const CAR_BRANDS = [
  'Alfa Romeo','Audi','BMW','Chevrolet','Chrysler','Citroën','Cupra',
  'Dacia','Daewoo','Dodge','DS','Fiat','Ford','Honda','Hyundai',
  'Infiniti','Jaguar','Jeep','Kia','Lada','Lamborghini','Land Rover',
  'Lexus','Maserati','Mazda','Mercedes-Benz','Mini','Mitsubishi',
  'Nissan','Opel','Peugeot','Porsche','Renault','Seat','Skoda',
  'Smart','Ssangyong','Subaru','Suzuki','Tesla','Toyota',
  'Volkswagen','Volvo','Aston Martin','Bentley','Ferrari',
  'Genesis','McLaren','Rolls-Royce','Saab','Zastava','Daihatsu',
  'Isuzu','Acura','Lincoln','Cadillac','Buick','GMC','Ram',
]

export const CAR_MODELS: Record<string, string[]> = {
  'Alfa Romeo': ['147','156','159','166','Giulia','Giulietta','Mito','Stelvio','Tonale'],
  'Audi': ['A1','A2','A3','A4','A5','A6','A7','A8','Q2','Q3','Q5','Q7','Q8','TT','R8','e-tron','Q4 e-tron'],
  'BMW': ['Seria 1','Seria 2','Seria 3','Seria 4','Seria 5','Seria 6','Seria 7','Seria 8','X1','X2','X3','X4','X5','X6','X7','Z4','M3','M5','iX','i4'],
  'Chevrolet': ['Aveo','Captiva','Cruze','Epica','Lacetti','Malibu','Spark','Trax'],
  'Chrysler': ['300C','Grand Voyager','Pacifica','Sebring','Voyager'],
  'Citroën': ['Berlingo','C1','C2','C3','C4','C5','C6','C3 Aircross','C5 Aircross','Jumper','Jumpy','Picasso','Spacetourer','Xsara'],
  'Cupra': ['Ateca','Born','Formentor','Leon'],
  'Dacia': ['Dokker','Duster','Jogger','Logan','Lodgy','Sandero','Spring','Bigster'],
  'Daewoo': ['Cielo','Espero','Kalos','Lacetti','Matiz','Nubira'],
  'Dodge': ['Caliber','Challenger','Charger','Durango','Journey','Nitro','Ram'],
  'DS': ['DS3','DS4','DS5','DS7','DS9'],
  'Fiat': ['500','500X','Bravo','Doblo','Ducato','Grande Punto','Linea','Panda','Punto','Scudo','Stilo','Tipo','Egea'],
  'Ford': ['B-Max','C-Max','EcoSport','Edge','Explorer','Fiesta','Focus','Galaxy','Ka','Ka+','Kuga','Mondeo','Mustang','Puma','Ranger','S-Max','Transit','Tourneo'],
  'Honda': ['Accord','City','Civic','CR-V','HR-V','Jazz','Legend','e'],
  'Hyundai': ['Accent','Elantra','i10','i20','i30','i40','ix20','ix35','Kona','Santa Fe','Sonata','Tucson','Ioniq','Ioniq 5','Ioniq 6'],
  'Infiniti': ['Q30','Q50','Q60','QX30','QX50','QX70'],
  'Jaguar': ['E-Pace','F-Pace','F-Type','I-Pace','S-Type','X-Type','XE','XF','XJ'],
  'Jeep': ['Cherokee','Commander','Compass','Grand Cherokee','Renegade','Wrangler','Avenger'],
  'Kia': ['Ceed','EV6','Niro','Optima','Picanto','Rio','Sorento','Soul','Sportage','Stinger','Stonic','Xceed','EV9'],
  'Lada': ['Granta','Kalina','Niva','Priora','Vesta'],
  'Lamborghini': ['Aventador','Huracan','Urus'],
  'Land Rover': ['Defender','Discovery','Discovery Sport','Freelander','Range Rover','Range Rover Evoque','Range Rover Sport','Range Rover Velar'],
  'Lexus': ['CT','ES','GS','IS','LC','LS','LX','NX','RX','UX'],
  'Maserati': ['Ghibli','GranTurismo','Grecale','Levante','Quattroporte'],
  'Mazda': ['2','3','5','6','CX-3','CX-5','CX-30','CX-60','MX-5','RX-8'],
  'Mercedes-Benz': ['A-Class','B-Class','C-Class','CLA','CLS','E-Class','G-Class','GLA','GLB','GLC','GLE','GLK','GLS','ML','S-Class','SL','SLK','Sprinter','Vito','EQA','EQB','EQC','EQE','EQS'],
  'Mini': ['Clubman','Cooper','Countryman','Paceman','Cabrio'],
  'Mitsubishi': ['ASX','Colt','Eclipse Cross','Galant','L200','Lancer','Outlander','Pajero','Space Star'],
  'Nissan': ['350Z','370Z','Ariya','Juke','Leaf','Micra','Murano','Navara','Note','Pathfinder','Patrol','Pulsar','Qashqai','Sentra','Terrano','Tiida','X-Trail'],
  'Opel': ['Adam','Agila','Astra','Cascada','Corsa','Crossland','Grandland','Insignia','Meriva','Mokka','Omega','Signum','Vectra','Vivaro','Zafira'],
  'Peugeot': ['107','108','2008','206','207','208','3008','306','307','308','4008','406','407','408','5008','508','Boxer','Expert','Partner','Rifter','e-208','e-2008'],
  'Porsche': ['718','911','Cayenne','Macan','Panamera','Taycan'],
  'Renault': ['Arkana','Captur','Clio','Duster','Espace','Fluence','Kadjar','Kangoo','Koleos','Laguna','Latitude','Logan','Master','Megane','Modus','Sandero','Scenic','Symbol','Trafic','Twingo','Zoe','Austral'],
  'Seat': ['Alhambra','Altea','Arona','Ateca','Cordoba','Exeo','Ibiza','Leon','Mii','Tarraco','Toledo'],
  'Skoda': ['Citigo','Enyaq','Fabia','Kamiq','Karoq','Kodiaq','Octavia','Rapid','Roomster','Scala','Superb','Yeti'],
  'Smart': ['Forfour','Fortwo','#1','#3'],
  'Ssangyong': ['Korando','Musso','Rexton','Tivoli','Torres','XLV'],
  'Subaru': ['Forester','Impreza','Legacy','Outback','WRX','XV','Solterra'],
  'Suzuki': ['Alto','Baleno','Grand Vitara','Ignis','Jimny','Splash','Swift','SX4','Vitara','S-Cross'],
  'Tesla': ['Model 3','Model S','Model X','Model Y','Cybertruck'],
  'Toyota': ['Auris','Avensis','Aygo','C-HR','Camry','Corolla','GR86','Hilux','Land Cruiser','Prius','ProAce','RAV4','Supra','Urban Cruiser','Verso','Yaris','bZ4X'],
  'Volkswagen': ['Amarok','Arteon','Caddy','Caravelle','CC','Crafter','Golf','ID.3','ID.4','ID.5','Jetta','Multivan','Passat','Phaeton','Polo','Scirocco','Sharan','T-Cross','T-Roc','Tiguan','Touareg','Touran','Transporter','Up'],
  'Volvo': ['C30','C40','S40','S60','S80','S90','V40','V50','V60','V70','V90','XC40','XC60','XC70','XC90','EX30','EX90'],
  'Aston Martin': ['DB11','DBS','DBX','Vantage'],
  'Bentley': ['Bentayga','Continental','Flying Spur','Mulsanne'],
  'Ferrari': ['296','488','812','F8','Portofino','Roma','SF90'],
  'Genesis': ['G70','G80','G90','GV70','GV80'],
  'McLaren': ['540C','570S','600LT','720S','Artura'],
  'Rolls-Royce': ['Cullinan','Dawn','Ghost','Phantom','Spectre','Wraith'],
  'Saab': ['9-3','9-5'],
}

export const CITIES = [
  'Alba Iulia','Alexandria','Arad','Bacău','Baia Mare','Bistrița','Botoșani',
  'Brăila','Brașov','București','Buzău','Cluj-Napoca','Constanța','Craiova',
  'Deva','Drobeta-Turnu Severin','Focșani','Galați','Giurgiu','Iași',
  'Miercurea Ciuc','Oradea','Piatra Neamț','Pitești','Ploiești','Râmnicu Vâlcea',
  'Reșița','Satu Mare','Sfântu Gheorghe','Sibiu','Slatina','Slobozia',
  'Suceava','Târgoviște','Târgu Jiu','Târgu Mureș','Timișoara','Tulcea',
  'Vaslui','Zalău','Alexandria','Câmpina','Câmpulung','Dej','Lugoj',
  'Mangalia','Mediaș','Odorheiu Secuiesc','Onești','Pașcani','Reghin',
  'Roman','Roșiorii de Vede','Sighetu Marmației','Sighișoara','Sinaia',
  'Turda','Turnu Măgurele','Urziceni','Vulcan','Zalău','Zimnicea',
]

export const FUEL_TYPES = ['Benzină','Diesel','Hybrid','Plug-in Hybrid','Electric','GPL','Bifuel']
